name: build
on: push
jobs:
  build_project:
    runs-on: manjaro-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v1
      - name: build 1
        run: |
          mkdir build 
          cd build 
          cmake .. 
          cmake  --build .

